### ISSUE TITLE
Crash on stream

### ISSUE THREAD

**Issue by oscar-b** [Trojan295/discord-airplay#3]
Got the following crash when I try to stream today:

```
{"level":"info","ts":"2023-09-26T17:58:44Z","caller":"airplay/airplay.go:111","msg":"airplay is now running.  Press CTRL-C to exit."}
{"level":"info","ts":"2023-09-26T17:58:44Z","logger":"interactionHandler","caller":"discord/interactions.go:81","msg":"connected to guild","guildID":"80555577431822336"}
panic: runtime error: makeslice: len out of range

goroutine 54 [running]:
github.com/Trojan295/discord-airplay/pkg/codec.StreamDCAData({0x84f2d8, 0xc00050a440}, {0x84a320, 0xc00011f560}, 0xc0004df4a0, 0xc0004be040)
	/src/pkg/codec/opus.go:34 +0x152
github.com/Trojan295/discord-airplay/pkg/discord.(*DiscordVoiceChatSession).SendAudio(0xc000030680, {0x84f2d8, 0xc00050a440}, {0x84a320, 0xc00011f560}, 0x0?)
	/src/pkg/discord/voicechat.go:61 +0xba
github.com/Trojan295/discord-airplay/pkg/bot.(*GuildPlayer).playPlaylist(0xc0001e8300, {0x84f2d8, 0xc000114440})
	/src/pkg/bot/player.go:329 +0x996
github.com/Trojan295/discord-airplay/pkg/bot.(*GuildPlayer).Run(0xc0001e8300, {0x84f2d8, 0xc000114440})
	/src/pkg/bot/player.go:267 +0x691
github.com/Trojan295/discord-airplay/pkg/discord.(*InteractionHandler).GuildCreate.func1()
	/src/pkg/discord/interactions.go:84 +0x3f
created by github.com/Trojan295/discord-airplay/pkg/discord.(*InteractionHandler).GuildCreate
	/src/pkg/discord/interactions.go:83 +0x1db
```

Any ideas?

**Comment by oscar-b** [comment]
Tried playing this: https://www.youtube.com/watch?v=AjiSzMFEDgo&pp=ygUNZGVhZG1hdTUgbGl2ZQ%3D%3D

**Comment by oscar-b** [comment]
I think it's related to the format of the link, if I use links generated via the "Sharing" thing on YT it works fine

**Comment by Trojan295** [comment]
@oscar-b I released `ghcr.io/trojan295/discord-airplay:v0.1.5`, which should fix this.
